runtime: nodejs20
env:     standard
instance_class: F2

handlers:

# User-supplied static assets
- url: /(.*\.(ico|jpg|jpeg|png|gif|webp|svg|woff2?|ttf|eot|xml|txt))$
  static_files: .output/public/\1
  upload:       .output/public/.*\.(ico|jpg|jpeg|png|gif|webp|svg|woff2?|ttf|eot|xml|txt)$
  expiration: 7d 0h
  secure: always
  redirect_http_response_code: 301

# 1️⃣  Manifest & other dynamic Nitro endpoints
- url: /_nuxt/builds/.*
  script: auto               # let your Node server generate the JSON

# 2️⃣  All remaining client assets (JS/CSS/fonts, etc.)
- url: /_nuxt/(.*)
  static_files: .output/public/_nuxt/\1
  upload:      .output/public/_nuxt/.*
  expiration: 30d 0h
  secure: always
  redirect_http_response_code: 301

# Catch-all → SSR
- url: /.*
  script: auto

entrypoint: npm run start    # Nuxt’s default runs `node .output/server/index.mjs`
automatic_scaling:
  min_instances: 0
  max_instances: 5
